voiver_roscones_homepage:
    path:     /hello/{name}
    defaults: { _controller: VoiverRosconesBundle:Default:index }

voiver_roscones_index:
    path: /roscones/index
    defaults: { _controller:  VoiverRosconesBundle:Roscones:index }